# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cmmbtSQVMBEv-tepElXelztLuH4r_16t
"""

# -*- coding: utf-8 -*-


# -*- coding: utf-8 -*-
import os
import numpy as np
import pandas as pd
import streamlit as st
import joblib

# (optional) dùng để suy luận schema input từ pipeline
try:
    from sklearn.compose import ColumnTransformer
except Exception:
    ColumnTransformer = None

st.set_page_config(page_title="Student-Mat | Regression dự đoán G3", layout="centered")
st.title("Dự đoán điểm cuối kỳ (G3)")
# =========================
# Helpers (đồng bộ với notebook)
# =========================
def add_absences_log1p(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    if "absences" in df.columns and "absences_log1p" not in df.columns:
        df["absences_log1p"] = np.log1p(df["absences"])
    return df

def map_paid_columns_for_pipeline(df: pd.DataFrame, pipe) -> pd.DataFrame:
    """
    Pipeline lúc train có thể dùng 'paid' hoặc 'paidclass'.
    Hàm này thử predict, nếu lỗi thiếu cột thì tự map.
    """
    df_try = df.copy()

    # thử trực tiếp
    try:
        _ = pipe.predict(df_try)
        return df_try
    except Exception:
        pass

    # thử paid -> paidclass
    df_try2 = df.copy()
    if "paid" in df_try2.columns and "paidclass" not in df_try2.columns:
        df_try2.rename(columns={"paid": "paidclass"}, inplace=True)
    try:
        _ = pipe.predict(df_try2)
        return df_try2
    except Exception:
        pass

    # thử paidclass -> paid
    df_try3 = df.copy()
    if "paidclass" in df_try3.columns and "paid" not in df_try3.columns:
        df_try3.rename(columns={"paidclass": "paid"}, inplace=True)

    # nếu vẫn lỗi sẽ raise để báo user
    _ = pipe.predict(df_try3)
    return df_try3

def infer_expected_columns(pipe):
    """Cố gắng suy luận danh sách cột đầu vào mà pipeline mong đợi.
    Trả về set[str] hoặc None nếu không suy luận được chắc chắn.
    """
    # sklearn Pipeline thường có feature_names_in_
    cols = None
    if hasattr(pipe, "feature_names_in_"):
        try:
            cols = set([str(c) for c in pipe.feature_names_in_])
            return cols
        except Exception:
            pass

    # thử tìm ColumnTransformer trong các bước
    if hasattr(pipe, "named_steps") and ColumnTransformer is not None:
        try:
            for _, step in pipe.named_steps.items():
                if ColumnTransformer is not None and isinstance(step, ColumnTransformer):
                    colset = set()
                    # transformers: list of (name, transformer, columns)
                    for tr in getattr(step, "transformers", []) or []:
                        if len(tr) >= 3:
                            columns = tr[2]
                            if isinstance(columns, (list, tuple)):
                                colset.update([str(c) for c in columns])
                            elif isinstance(columns, slice):
                                # không suy luận được chắc chắn với slice
                                return None
                            else:
                                # có thể là string
                                colset.add(str(columns))
                    return colset if colset else None
        except Exception:
            pass

    return None

def infer_requires_g1g2(pipe) -> bool:
    """True nếu pipeline có vẻ sử dụng G1/G2; False nếu có vẻ không dùng.
    Nếu không suy luận được, mặc định True (giữ tương thích với app cũ).
    """
    cols = infer_expected_columns(pipe)
    if cols is None:
        return True
    return ("G1" in cols) or ("G2" in cols)

# =========================
# Load pipeline
# =========================
st.sidebar.header("Chọn mô hình")
model_choice = st.sidebar.radio(
    "Chế độ chạy",
    ["Tự động (theo model)", "Model đầy đủ (có G1, G2)", "Model B1 (không G1, G2)"],
    index=0,
)
st.sidebar.markdown("---")

st.sidebar.header("Load model regression (.pkl)")
pkl_upload = st.sidebar.file_uploader("Upload pipeline .pkl (khuyên dùng)", type=["pkl"])

MODEL_FULL_PATH = "student_g3.pkl"
MODEL_B1_PATH = "student_g3_model_b1_no_g1g2.pkl"

# DEFAULT_PATH sẽ được chọn theo model_choice (trừ khi user upload pkl)
DEFAULT_PATH = MODEL_FULL_PATH

@st.cache_resource
def load_pipeline_from_upload(file_obj):
    return joblib.load(file_obj)

@st.cache_resource
def load_pipeline_from_path(path: str):
    return joblib.load(path)

pipe = None
if pkl_upload is not None:
    try:
        pipe = load_pipeline_from_upload(pkl_upload)
        st.sidebar.success("Đã load pipeline từ file upload.")
    except Exception as e:
        st.sidebar.error(f"Không load được file upload: {e}")
        st.stop()
else:
    # Chọn model mặc định theo lựa chọn user (khi KHÔNG upload)
    if model_choice == "Model B1 (không G1, G2)":
        DEFAULT_PATH = MODEL_B1_PATH
    else:
        DEFAULT_PATH = MODEL_FULL_PATH

    if os.path.exists(DEFAULT_PATH):
        try:
            pipe = load_pipeline_from_path(DEFAULT_PATH)
            st.sidebar.success(f"Đã load pipeline từ: {DEFAULT_PATH}")
        except Exception as e:
            st.sidebar.error(f"Không load được {DEFAULT_PATH}: {e}")
            st.stop()
    else:
        st.sidebar.error(
            f"Không tìm thấy '{DEFAULT_PATH}'.\n"
            "Hãy upload file .pkl ở trên hoặc đặt student_g3.pkl cùng thư mục app."
        )
        st.stop()

# =========================
# Suy luận chế độ theo model (Auto) và áp dụng lựa chọn user
# =========================
auto_requires_g1g2 = infer_requires_g1g2(pipe)

if model_choice == "Model đầy đủ (có G1, G2)":
    effective_requires_g1g2 = True
elif model_choice == "Model B1 (không G1, G2)":
    effective_requires_g1g2 = False
else:
    effective_requires_g1g2 = auto_requires_g1g2

st.sidebar.info(
    "Chế độ input hiện tại: "
    + ("Có G1/G2" if effective_requires_g1g2 else "Không có G1/G2 (B1)")
    + (" (auto)" if model_choice == "Tự động (theo model)" else "")
)


# =========================
# UI nhập liệu
# =========================
with st.sidebar:
    st.header("Nhập thông tin học sinh")

    # =========================
    # Categorical (đã bỏ: school, Pstatus, nursery, reason, famrel)
    # =========================
    sex = st.selectbox("sex", ["F", "M"])
    address = st.selectbox("address", ["U", "R"])
    famsize = st.selectbox("famsize", ["LE3", "GT3"])

    Mjob = st.selectbox("Mjob", ["teacher", "health", "services", "at_home", "other"])
    Fjob = st.selectbox("Fjob", ["teacher", "health", "services", "at_home", "other"])
    guardian = st.selectbox("guardian", ["mother", "father", "other"])

    schoolsup = st.selectbox("schoolsup", ["yes", "no"])
    famsup = st.selectbox("famsup", ["yes", "no"])
    paid = st.selectbox("paid (hoặc paidclass)", ["yes", "no"])
    activities = st.selectbox("activities", ["yes", "no"])
    higher = st.selectbox("higher", ["yes", "no"])
    internet = st.selectbox("internet", ["yes", "no"])
    romantic = st.selectbox("romantic", ["yes", "no"])

    st.markdown("---")
    st.subheader("Numeric / Ordinal")

    # =========================
    # Numeric/Ordinal (đã bỏ: age, famrel)
    # =========================
    Medu = st.slider("Medu (0-4)", 0, 4, 2)
    Fedu = st.slider("Fedu (0-4)", 0, 4, 2)

    traveltime = st.slider("traveltime (1-4)", 1, 4, 1)
    studytime = st.slider("studytime (1-4)", 1, 4, 2)
    failures = st.slider("failures (0-3)", 0, 3, 0)

    freetime = st.slider("freetime (1-5)", 1, 5, 3)
    goout = st.slider("goout (1-5)", 1, 5, 3)
    Dalc = st.slider("Dalc (1-5)", 1, 5, 1)
    Walc = st.slider("Walc (1-5)", 1, 5, 1)
    health = st.slider("health (1-5)", 1, 5, 3)

    absences = st.slider("absences", 0, 93, 4)

    if effective_requires_g1g2:
        G1 = st.slider("G1 (0-20)", 0, 20, 10)
        G2 = st.slider("G2 (0-20)", 0, 20, 10)
    else:
        G1, G2 = None, None

# =========================
# Predict
# =========================
st.markdown("---")
col1, col2, col3 = st.columns([1, 2, 1])
with col2:
    predict_button = st.button("Dự đoán G3")

if predict_button:
    # Schema đã loại bỏ: school, Pstatus, nursery, reason, famrel, age
    input_data = {
        "sex": sex,
        "address": address,
        "famsize": famsize,
        "Medu": Medu,
        "Fedu": Fedu,
        "Mjob": Mjob,
        "Fjob": Fjob,
        "guardian": guardian,
        "traveltime": traveltime,
        "studytime": studytime,
        "failures": failures,
        "schoolsup": schoolsup,
        "famsup": famsup,
        "paid": paid,
        "activities": activities,
        "higher": higher,
        "internet": internet,
        "romantic": romantic,
        "freetime": freetime,
        "goout": goout,
        "Dalc": Dalc,
        "Walc": Walc,
        "health": health,
        "absences": absences,
    }

    # Chỉ thêm G1/G2 nếu mô hình yêu cầu
    if effective_requires_g1g2:
        input_data["G1"] = G1
        input_data["G2"] = G2

    input_df = pd.DataFrame([input_data])
    input_df = add_absences_log1p(input_df)

    st.subheader("Dữ liệu đã nhập")
    st.dataframe(input_df, hide_index=True)

    try:
        # tự map paid/paidclass cho khớp pipeline (nếu pipeline dùng paidclass)
        input_df = map_paid_columns_for_pipeline(input_df, pipe)

        pred = float(pipe.predict(input_df)[0])
        st.subheader("Kết quả dự đoán")
        st.write(f"Điểm G3 dự đoán: **{pred:.2f}**")
    except Exception as e:
        st.error(f"Lỗi khi dự đoán: {e}")
        st.info(
            "Nếu lỗi liên quan thiếu cột/không khớp schema: "
            "hãy đảm bảo pipeline (.pkl) được train với đúng các cột hiện tại của app "
            "(sau khi bạn đã drop các feature)."
        )